name: Elixir CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: 'trust'
          POSTGRES_DB: ironiauth_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.17'
        otp-version: '27'

    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile
      run: mix compile --warnings-as-errors
      env:
        MIX_ENV: test

    - name: Setup database
      run: |
        mix ecto.create
        mix ecto.migrate
      env:
        MIX_ENV: test
        PGHOST: localhost
        GUARDIAN_RSA_PRIVATE_KEY: ${{ secrets.GUARDIAN_RSA_PRIVATE_KEY }}

    - name: Run tests
      run: mix test
      env:
        MIX_ENV: test
        PGHOST: localhost
        GUARDIAN_RSA_PRIVATE_KEY: ${{ secrets.GUARDIAN_RSA_PRIVATE_KEY }}
